---
- name: Create nginx exp system group
  group:
    name: nginx-exp
    state: present

- name: Create nginx system user member of nginx exp group
  user:
    name: nginx-exp
    group: nginx-exp

- name: Download nginx exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /home/nginx-exp/

- name: Extract nginx exporter
  become: true
  unarchive:
    src: /home/nginx-exp/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Create nginx exporter service file
  become: true
  template:
    src: /home/dchoi/github/ansible-role-nginx-draft/templates/nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: Start Exporter
  systemd:
    state: started
    name: nginx_exporter

- name: fail playbook when GET request to port 9113/metrics does not return nginx_up 1
  uri:
    url: http://localhost:9113/metrics
    return_content: true
  register: this
  failed_when: "'nginx_up 1' not in this.content"

- name: fail playbook when GET request to port 80 (web server default home page) does not return status code 200.
  uri:
    url: http://localhost:80
  failed_when: "webpage.status != 200"
